-- ══════════════════════════════════════════════════════════════════════
-- PDF LIBRARY  —  table + storage bucket for the in-app PDF library
--
-- Every report generated by Print.render()/renderNewTab() (js/print.js)
-- gets offered up for saving into a synced library: js/pdf-library.js
-- uploads the blob to the `pdf-library` Storage bucket and inserts one
-- row here with the metadata the library UI (#page-pdf-library) filters,
-- searches, and displays. A client-side sweep (runExpirySweep(), called
-- once on app boot from auth.js's unlockApp()) deletes both the row and
-- the storage object once expires_at is in the past — unless pinned.
--
-- Same Supabase project this whole app already syncs everything else to
-- (see SB_URL/SB_KEY in js/supabase.js) — no new project needed. Uses
-- the anon/publishable key client-side, same trust model as every other
-- table this app touches: Row Level Security below is what actually
-- scopes access, not key secrecy.
--
-- Run this once, by hand, in the Supabase SQL editor for this project
-- (see DEPLOY.md in this folder for the storage bucket step, which the
-- dashboard UI does more reliably than SQL).
-- ══════════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto; -- gen_random_uuid()

create table if not exists public.bt_pdf_library (
  id           uuid primary key default gen_random_uuid(),
  category     text not null default 'other',   -- 'sales' | 'manager' | 'inventory' | 'closing' | 'audit' | 'notesheets' | 'other'
  title        text,                             -- human title, e.g. report's <title> or filename stem
  filename     text not null,                    -- the .pdf filename as saved
  storage_path text not null,                     -- path inside the pdf-library bucket
  size_bytes   bigint,
  pinned       boolean not null default false,    -- "Keep" — never swept
  created_at   timestamptz not null default now(),
  expires_at   timestamptz                        -- null only makes sense when pinned = true
);

create index if not exists bt_pdf_library_category_idx  on public.bt_pdf_library (category);
create index if not exists bt_pdf_library_expires_idx   on public.bt_pdf_library (expires_at);
create index if not exists bt_pdf_library_created_idx   on public.bt_pdf_library (created_at desc);

alter table public.bt_pdf_library enable row level security;

-- Anonymous/publishable-key access, same as every other table in this
-- app (bt_salesdata, inventory_products, etc.) — single shared team,
-- no per-user auth layer in this app.
drop policy if exists bt_pdf_library_select on public.bt_pdf_library;
create policy bt_pdf_library_select on public.bt_pdf_library
  for select using (true);

drop policy if exists bt_pdf_library_insert on public.bt_pdf_library;
create policy bt_pdf_library_insert on public.bt_pdf_library
  for insert with check (true);

drop policy if exists bt_pdf_library_update on public.bt_pdf_library;
create policy bt_pdf_library_update on public.bt_pdf_library
  for update using (true) with check (true);

drop policy if exists bt_pdf_library_delete on public.bt_pdf_library;
create policy bt_pdf_library_delete on public.bt_pdf_library
  for delete using (true);

-- ── Storage bucket ───────────────────────────────────────────────────
-- Prefer creating this in Dashboard → Storage → New bucket (see
-- DEPLOY.md) — the insert below is a fallback for SQL-only setups and
-- is a no-op if the bucket already exists.
insert into storage.buckets (id, name, public)
values ('pdf-library', 'pdf-library', true)
on conflict (id) do nothing;

drop policy if exists bt_pdf_library_storage_select on storage.objects;
create policy bt_pdf_library_storage_select on storage.objects
  for select using (bucket_id = 'pdf-library');

drop policy if exists bt_pdf_library_storage_insert on storage.objects;
create policy bt_pdf_library_storage_insert on storage.objects
  for insert with check (bucket_id = 'pdf-library');

drop policy if exists bt_pdf_library_storage_delete on storage.objects;
create policy bt_pdf_library_storage_delete on storage.objects
  for delete using (bucket_id = 'pdf-library');
